name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "task1"
  title = "This is a new feature"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "d7tf6zdjnvwchacf938c5eed"
  title = "Add more collect"
  description = ""
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "task2"
  title = "This is a bug should be repair"
  description = "<p></p>"
  tag = "bug"
  linkFiles = [ "\\Hemy.Lib.V2\\Core\\Context.cs" ]
  dueDate = ""
  priority = ""
  linkCommits = [ ]

    [[processes.tasks.checkList]]
    id = "gnlreqjvtzslfxnkwhu42ot6"
    title = "Essai 1"
    completed = false

[[processes]]
id = "process3"
name = "Done"
tasks = [ ]
